package com.riskanalysis.risk_system.controller;

import com.riskanalysis.risk_system.model.Notification;
import com.riskanalysis.risk_system.service.NotificationService;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
@RequestMapping("/api/notifications")
@CrossOrigin(origins = "http://localhost:3000")
public class NotificationController {

    private final NotificationService notificationService;

    public NotificationController(NotificationService notificationService){
        this.notificationService = notificationService;
    }

    // CREATE NOTIFICATION (optional, usually auto-generated by High risks)
    @PostMapping
    public Notification createNotification(@RequestBody Notification notification){
        return notificationService.saveNotification(notification);
    }

    // GET ALL NOTIFICATIONS
    @GetMapping
    public List<Notification> getNotifications(){
        return notificationService.getAllNotifications();
    }

    // GET ONLY UNREAD NOTIFICATIONS
    @GetMapping("/unread")
    public List<Notification> getUnreadNotifications() {
        return notificationService.getUnreadNotifications();
    }

    // MARK NOTIFICATION AS READ
    @PutMapping("/{id}/read")
    public Notification markAsRead(@PathVariable Long id) {
        return notificationService.markAsRead(id);
    }

    // DELETE NOTIFICATION
    @DeleteMapping("/{id}")
    public String deleteNotification(@PathVariable Long id) {
        notificationService.deleteNotification(id);
        return "Notification deleted successfully";
    }
}